version: "3.9"

services:
  front:
    build: ./kalory-frontend/
    ports:
      - "3000:3000"
  api:
    restart: always
    build: ./kalory-backend/
    ports:
      - "8080:8080"
    links:
      - "db:database"
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: MySuperPassword1!
    ports:
      - "5432:5432"
