version: "3.9"

services:
  nginx:
    restart: always
    build:
      context: ./kalory-nginx/
    ports:
      - "80:80"
    links:
      - "kalory-frontend:frontend"
      - "kalory-backend:backend"
  front:
    build: ./kalory-frontend/
    ports:
      - "5000:5000"
  api:
    restart: always
    build: ./kalory-backend/
    ports:
      - "8080:8080"
    links:
      - "db:database"
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: MySuperPassword1!
    ports:
      - "5432:5432"
